spring:
  application:
    name: user-service
  server:
    port: 8081
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: parth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 436274334861-782058r34orv1r49tpeu6trarqrkd5e8.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  data:
    mongodb:
      uri: mongodb+srv://2021parthkadam:VfwwJ3uV0l0C6l1O@cluster0.oc0ol.mongodb.net/user_service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
        web: DEBUG

jwt:
  secret: e8c434c4c2ed4e4e97ccb1af6a2d4998
  expiration: 31536000000

resilience4j:
  rateLimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 60s
        timeoutDuration: 0
