spring:
  application:
    name: product_service
  server:
    port: 8082
  data:
    mongodb:
      uri: mongodb+srv://2021parthkadam:VfwwJ3uV0l0C6l1O@cluster0.oc0ol.mongodb.net/product_service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false # Prevents errors on empty beans
  logging:
    level:
      org:
        springframework:
          web: DEBUG
      com:
        hypehouse: DEBUG
  mongodb:
    repositories:
      enabled: true

algolia:
  application-id: G66MRCQA66
  api-key: d27560c743bf7452ca8240669dd9ddb1
