spring:
  application:
    name: product_service
  server:
    port: 8082
  data:
    mongodb:
      uri: mongodb+srv://=
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false # Prevents errors on empty beans
  logging:
    level:
      org:
        springframework:
          web: DEBUG
      com:
        hypehouse: DEBUG
  mongodb:
    repositories:
      enabled: true

algolia:
  application-id:
  api-key:
