spring:
  application:
    name: inventory_service
  server:
    port: 8083
  data:
    mongodb:
      uri: mongodb+srv://2021parthkadam:VfwwJ3uV0l0C6l1O@cluster0.oc0ol.mongodb.net/inventory_service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false # Prevents errors on empty beans
  logging:
    level:
      org:
        springframework:
          security: DEBUG
          web: DEBUG
      com:
        hypehouse: DEBUG
      org.springframework.data.mongodb: TRACE
  mongodb:
    repositories:
      enabled: true
grpc:
  server:
    port: 9090
    security:
      enabled: false
    negotiationType: PLAINTEXT

